server:
  port: 8080
  servlet:
    context-path: /api

management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /features
      exposure:
        include: "health,info,metrics,logfile"